apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
  namespace: techtalk
  labels:
    app: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: registry.gitlab.com/leonardosimoura-pessoal/glicemic/simple-app:$BUILD_BUILDNUMBER
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  namespace: techtalk
spec:
  selector:
    app: simple-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  name: "simple-app-ingress"
  namespace: techtalk
spec:
  rules:
    - host: simpleapp.glicemic.com.br
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: "simple-app-service"
              port:
                number: 80
  tls:
  - hosts:
    - simpleapp.glicemic.com.br
    secretName: simpleapp-cert